#!/bin/bash

# $1 测试总组数
# $2 测试的起始规模
# $3 每组测试的增量
# $4 每组测试的重复次数

echo $1 $2 $3 $4
n=$2    # 不能有空格
for i in $(seq 1 $1)   # $后为数据集，从1到10的整数
do
    echo "size: $n"
    ./test $4 $n | grep time | ../stat/main
    n=$((n+$3))    # 不能有空格
done
